services:
  - type: web
    name: xl-lab-api
    runtime: python
    python:
      pythonVersion: "3.9.0"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: ALLOWED_ORIGINS
        value: "https://servicewechat.com,https://www.weixin.qq.com"